# Automação de Sistemas e Processos com Python

### Desafio:

Todos os dias, o nosso sistema atualiza as vendas do dia anterior.
O seu trabalho diário, como analista, é enviar um e-mail para a diretoria, assim que começar a trabalhar, com o faturamento e a quantidade de produtos vendidos no dia anterior

E-mail da diretoria: seugmail+diretoria@gmail.com<br>
Local onde o sistema disponibiliza as vendas do dia anterior: https://drive.google.com/drive/folders/149xknr9JvrlEnhNWO49zPcw0PW5icxga

Para resolver isso, vamos usar o pyautogui, uma biblioteca de automação de comandos do mouse e do teclado


Referência do pyautogui: https://pyautogui.readthedocs.io/en/latest/quickstart.html

In [58]:
#pyautogui->automações
#pandas ->dados
#openpyxl->trabalhar com bases de dados em excel
#para instalar: abrir o terminal e rodar: pip install pandas pyautogui openpyxl

In [59]:




import pyautogui
import time

#pyautogui.click -> clicar com o mouse
#pyautogui.write -> escrever
#pyautogui.hotkey -> combinação de teclas
#pyautogui.press -> aperta uma tecla 

# Passo a passo do desafio

# Passo 1: Entrar no sistema da empresa(link do drive)
#abri o chrome
pyautogui.press("win") 
pyautogui.write("microsoft edge")
pyautogui.press("enter")
#digitei o link do sistema
link = "https://drive.google.com/drive/folders/149xknr9JvrlEnhNWO49zPcw0PW5icxga"
#apertei enter e esperei
time.sleep(2)
pyautogui.write(link)
pyautogui.press("enter")

In [60]:
# Passo 2: Navegar no sistema para encontrar a base de dados
time.sleep(10)
pyautogui.click(x=458, y=413, clicks=2)
time.sleep(5)



# Passo 3: Exportar a base de dados ( baixar o arquivo)
time.sleep(5)
pyautogui.click(x=1780, y=406, clicks=2)
time.sleep(2)
pyautogui.click(x=1551, y=512, clicks=2)

### Vamos agora ler o arquivo baixado para pegar os indicadores

- Faturamento
- Quantidade de Produtos

In [61]:
import pandas

# Passo 4: Calcular os indicadores ( faturamento e qnt de prod vendidos)
#abrir a base de dados
caminho = r"C:\Users\caeta\Downloads\Vendas - Dez (1).xlsx"
tabela = pandas.read_excel(caminho)

#ver as informações da base de dados
display(tabela)

#somar o faturamento
faturamento = tabela["Valor Final"].sum()

#somar a quantidade de produtos
qtde_produtos = tabela["Quantidade"].sum()


print(faturamento)
print(qtde_produtos)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

2917311
15227

In [62]:
import pandas

# Passo 4: Calcular os indicadores ( faturamento e qnt de prod vendidos)
#abrir a base de dados
caminho = r"C:\Users\caeta\Downloads\Vendas - Dez (1).xlsx"
tabela = pandas.read_excel(caminho)

#ver as informações da base de dados
display(tabela)

#somar o faturamento
faturamento = tabela["Valor Final"].sum()

#somar a quantidade de produtos
qtde_produtos = tabela["Quantidade"].sum()


print(faturamento)
print(qtde_produtos)

,Código Venda,Data,ID Loja,Produto,Quantidade,Valor Unitário,Valor Final
0,65014,2019-12-01,Shopping Morumbi,Sunga Listrado,5,114,570
1,65014,2019-12-01,Shopping Morumbi,Casaco Listrado,1,269,269
2,65016,2019-12-01,Iguatemi Campinas,Sapato Listrado,2,363,726
3,65016,2019-12-01,Iguatemi Campinas,Casaco,1,250,250
4,65017,2019-12-01,Shopping SP Market,Gorro Liso,3,92,276
...,...,...,...,...,...,...,...
7084,69996,2019-12-26,Center Shopping Uberlândia,Short Listrado,2,102,204
7085,69996,2019-12-26,Center Shopping Uberlândia,Mochila,4,270,1080
7086,69996,2019-12-26,Center Shopping Uberlândia,Pulseira Estampa,1,87,87
7087,69997,2019-12-26,Ribeirão Shopping,Camisa Listrado,1,108,108
7088,69997,2019-12-26,Ribeirão Shopping,Short Linho,2,133,266

2917311
15227

### Vamos agora enviar um e-mail pelo gmail

In [ ]:
import pyautogui
import time
import pyperclip

# Passo 5: Enviar as informações por e-mail
#abrir email
pyautogui.hotkey("ctrl","t") 
time.sleep(1)
pyautogui.write("mail")
pyautogui.press("enter")
time.sleep(10)
#botão escrever
pyautogui.click(x=206, y=209, clicks=1) 
time.sleep(2)
#mandar o email para
pyautogui.write("cleitonrodhjpareira@gmail.com",interval=0.05)
pyautogui.press("tab")
time.sleep(2)
pyautogui.press("tab")
#Assunto
pyperclip.copy("Relatório de Vendas")
pyautogui.hotkey("ctrl","v")
time.sleep(2)
pyautogui.press("tab")
time.sleep(2)
#corpo do email
texto = f"""
Prezados,

Segue o relatório de vendas de hoje
Faturamento= {faturamento:,.2f} 
Quantidade de produtos= {qtde_produtos:,}

estou aqui para qualquer dúvida
Abs, CD da rua velha
"""
pyperclip.copy(texto)
pyautogui.hotkey("ctrl","v")
#enviar
pyautogui.click(x=1201, y=968)

#### Use esse código para descobrir qual a posição de um item que queira clicar

- Lembre-se: a posição na sua tela é diferente da posição na minha tela

In [64]:
import pyautogui
import time
time.sleep(5)
print(pyautogui.position())

Point(x=1201, y=968)